# Build
custom_build(
    # Name of the container image
    ref = 'dispatcher-service',
    # Command to build the container image using Maven and Docker
    # On Windows, use %EXPECTED_REF% for the image name
    command = 'mvn clean install && docker build . -t %EXPECTED_REF%',
    # Files to watch that trigger a new build
    deps = ['pom.xml', 'src']
)

# Deploy
k8s_yaml(['k8s/deployment.yml', 'k8s/service.yml'])

# Manage
k8s_resource('dispatcher-service', port_forwards=['9003'])
