
services:
  polar-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - polar-network
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf


  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - 6379:6379
    networks:
      - polar-network



  edge-service:
    depends_on:
      - polar-redis
      - config-service
      - catalog-service
      - order-service
    image: "edge-service"
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATA_REDIS_HOST=polar-redis
    networks:
      - polar-network


  catalog-service:
    image: "catalog-service"
    depends_on:
      - polar-postgres
      - config-service
    ports:
      - 9001:9001
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - LOGGING_LEVEL_ROOT=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG
    networks:
      - polar-network


  order-service:
    image: "order-service"
    depends_on:
      - polar-postgres
      - config-service
    ports:
      - 9002:9002
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - LOGGING_LEVEL_ROOT=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG
    networks:
      - polar-network

  config-service:
    image: "config-service"
    ports:
      - 8888:8888
    networks:
      - polar-network

  polar-postgres:
    image: "postgres:14.12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - polar-network

networks:
  polar-network:
    driver: bridge

